import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { AuthProvider } from '@/context/AuthContext'; // 1. AuthProvider를 import


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider> {/* 2. AuthProvider로 감싸줍니다. */}
          {/* 2. Header 컴포넌트를 body 태그 바로 아래에, children 위에 추가합니다. */}
          <Header />
          {/* 3. {children}이 바로 각 페이지(page.tsx)의 실제 내용이 들어오는 자리입니다. */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
